import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { Spinner } from "../components/Spinner";
import { api } from "../utils/api";

const Success: NextPage = () => {
  const router = useRouter();
  const email = router.query.email as string;

  const isPaid = api.payment.isPaidEmail.useQuery(
    { email },
    {
      enabled: email !== undefined,
      refetchOnWindowFocus: false,
      refetchInterval: (data) => {
        return data?.isValid ? false : 2000;
      },
    }
  );

  const downloadUrl = api.payment.getDownloadUrl.useQuery(
    { email },
    {
      enabled: email !== undefined && isPaid.data?.isValid,
      refetchOnWindowFocus: false,
    }
  );

  console.log(downloadUrl.data);

  return (
    <>
      <Head>
        <title>Download your Content</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center text-white">
        {isPaid.data?.isValid ? (
          <div>
            <a href={downloadUrl.data}>link to s3 zip here</a>
          </div>
        ) : (
          <div className="flex flex-col items-center gap-4">
            <Spinner />
            Validating email...
          </div>
        )}
      </main>
    </>
  );
};

export default Success;
