import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Spinner } from "../components/Spinner";
import { useSession } from "../hooks/useSession";
import { api } from "../utils/api";

const Success: NextPage = () => {
  const { session } = useSession();

  const isPaid = api.payment.isPaidEmail.useQuery(
    { email: session },
    {
      enabled: !!session,
      refetchOnWindowFocus: false,
      refetchInterval: (data) => {
        return data?.isValid ? false : 2000;
      },
    }
  );

  const downloadUrl = api.payment.getDownloadUrl.useQuery(
    { email: session },
    {
      enabled: !!session && isPaid.data?.isValid,
      refetchOnWindowFocus: false,
    }
  );

  return (
    <>
      <Head>
        <title>Download your Content</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center gap-12 pt-24 text-white">
        {isPaid.data?.isValid ? (
          <>
            <Image
              src="/download.svg"
              width="300"
              height="300"
              alt="download image"
            />
            <h1 className="text-4xl">Your download is ready!</h1>
            <div className="">
              Click here to{" "}
              <a
                className="text-wdc-primary-darker hover:text-wdc-primary"
                href={downloadUrl.data}
              >
                download
              </a>{" "}
              the materials you purchased.
            </div>
          </>
        ) : (
          <div className="flex flex-col items-center gap-4">
            <Spinner />
            Validating email...
          </div>
        )}
      </main>
    </>
  );
};

export default Success;
