import { type NextPage } from "next";
import Head from "next/head";
import { type Stripe, loadStripe } from "@stripe/stripe-js";
import { useMemo } from "react";
import { api } from "../utils/api";
import { env } from "../env/client.mjs";
import Image from "next/image";
import { Spinner } from "../components/Spinner";
import { useSession } from "../hooks/useSession";
import Link from "next/link";

const useStripe = () => {
  const stripe = useMemo<Promise<Stripe | null>>(
    () => loadStripe(env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY),
    []
  );

  return stripe;
};

const Home: NextPage = () => {
  const createCheckout = api.payment.createCheckout.useMutation();
  const stripePromise = useStripe();
  const { session } = useSession();

  async function checkout() {
    const response = await createCheckout.mutateAsync();
    const stripe = await stripePromise;

    if (stripe !== null) {
      await stripe.redirectToCheckout({
        sessionId: response.id,
      });
    }
  }

  return (
    <>
      <Head>
        <title>Icon Generator DLC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center">
        <section className="container m-auto grid min-h-screen max-w-screen-lg grid-cols-2 items-start gap-20 pt-24 pb-24">
          <div className="flex flex-col gap-4">
            <h1 className="text-4xl text-white">Icon Generator DLC</h1>

            <p className="mb-6 text-xl font-normal text-white">
              Pay to gain access to the full code used to create the{" "}
              <a
                className="text-wdc-primary"
                target="_blank"
                rel="noreferrer"
                href="https://icon-generator.webdevcody.com"
              >
                https://icon-generator.webdevcody.com
              </a>{" "}
              web application.
              <br />
              <br />
              This application uses uses AI (DALL-E) to generate icons, Stripe
              to collect payments, SQL to store data, S3 for storing objects,
              AWS Amplify for hosting the next application. It written using
              some of the latest web technologies including: Next.js, Tailwind
              CSS, Prisma, Typescript, and tRPC.
            </p>

            {!session ? (
              <button
                className="rounded bg-gradient-to-r from-wdc-primary-darker to-blue-400 px-4 py-3 text-xl text-white hover:to-blue-500"
                disabled={createCheckout.isLoading}
                onClick={() => {
                  checkout().catch(console.error);
                }}
              >
                {createCheckout.isLoading ? <Spinner /> : <span>$59.00</span>}
              </button>
            ) : (
              <Link href="/dlc">
                <button
                  className="w-full rounded bg-gradient-to-r from-wdc-primary-darker to-blue-400 px-4 py-3 text-xl text-white hover:to-blue-500"
                  disabled={createCheckout.isLoading}
                  onClick={() => {
                    checkout().catch(console.error);
                  }}
                >
                  View Your Content
                </button>
              </Link>
            )}
          </div>

          <Image
            width="400"
            height="400"
            className="mx-auto w-full rounded-lg border border-white"
            alt="a picture of a person at a computer"
            src="/generator.png"
          />
        </section>
      </main>
    </>
  );
};

export default Home;
